name: Website CD
on:
  push:
    branches:
    - main
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run deploy script
      uses: maddox/actions/ssh@master
      env:
        HOST: ${{ secrets.HOST }}
        PORT: ${{ secrets.PORT }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        USER: ${{ secrets.USER }}
      with:
        args: 'cd personal-site && ./build.sh'