name: Website CD
on:
  push:
    branches:
    - main
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Run deploy script
      uses: maddox/actions/ssh@master
      env:
        HOST: ${{ secrets.HOST }}
        PORT: ${{ secrets.PORT }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        USER: ${{ secrets.USER }}
      with:
        args: 'cd SlimeBot && ./build.sh'